package com.patbaumgartner.mytunes.stations;

import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * The station catalogue: eight categories, each holding several channels.
 * <p>
 * The third-party channels come from three providers — SomaFM, Nightride FM and Radio
 * Paradise — whose streams answer browser requests with an audio content type and
 * permissive CORS; {@code tools/generate-stations.py} re-verifies every committed stream
 * the way a browser would use it and proposes further candidates from the open Radio
 * Browser directory. No stream URL carries credentials of any kind, which
 * {@code StationCatalogueTests} enforces. Every category <em>leads</em> with a channel
 * generated by {@code tools/generate-audio.py} and served from this repository, so real
 * playback can always be demonstrated in every category, offline, with no third-party
 * dependency and no licensing question.
 */
@Service
public class StationCatalogue {

	private static final String GENERATED = "Original loop generated for myTunes by tools/generate-audio.py";

	private static final String SOMAFM = "SomaFM";

	private static final String NIGHTRIDE = "Nightride FM";

	private static final String RADIO_PARADISE = "Radio Paradise";

	private static final List<Station> STATIONS = List.of(
			// Ambient
			new Station("mytunes-signal", "myTunes Signal", "Ambient / Generated", "Ambient",
					"audio/mytunes-signal.mp3", GENERATED),
			new Station("dronezone", "Drone Zone", "Atmospheric", "Ambient",
					"https://ice1.somafm.com/dronezone-128-mp3", SOMAFM),
			new Station("deepspaceone", "Deep Space One", "Deep Ambient", "Ambient",
					"https://ice1.somafm.com/deepspaceone-128-mp3", SOMAFM),
			new Station("synphaera", "Synphaera", "Space Ambient", "Ambient",
					"https://ice1.somafm.com/synphaera-128-mp3", SOMAFM),
			// Chill
			new Station("mytunes-lofi", "myTunes Lo-Fi", "Lo-Fi / Generated", "Chill", "audio/mytunes-lofi.mp3",
					GENERATED),
			new Station("groovesalad", "Groove Salad", "Ambient / Downtempo", "Chill",
					"https://ice1.somafm.com/groovesalad-128-mp3", SOMAFM),
			new Station("lush", "Lush", "Vocal / Dreampop", "Chill", "https://ice1.somafm.com/lush-128-mp3", SOMAFM),
			new Station("fluid", "Fluid", "Instrumental Hip-Hop", "Chill", "https://ice1.somafm.com/fluid-128-mp3",
					SOMAFM),
			new Station("chillsynth", "Chillsynth FM", "Chillsynth / Lo-Fi Synth", "Chill",
					"https://stream.nightride.fm/chillsynth.mp3", NIGHTRIDE),
			new Station("rp-mellow", "Radio Paradise Mellow", "Mellow Eclectic", "Chill",
					"https://stream.radioparadise.com/mellow-128", RADIO_PARADISE),
			// Beats
			new Station("mytunes-beats", "myTunes Beats", "Downtempo / Generated", "Beats", "audio/mytunes-beats.mp3",
					GENERATED),
			new Station("beatblender", "Beat Blender", "Deep House / Downtempo", "Beats",
					"https://ice1.somafm.com/beatblender-128-mp3", SOMAFM),
			new Station("rp-global", "Radio Paradise Global", "Global / World Beats", "Beats",
					"https://stream.radioparadise.com/global-128", RADIO_PARADISE),
			// Bass
			new Station("mytunes-subsignal", "myTunes Sub Signal", "Bass / Generated", "Bass",
					"audio/mytunes-subsignal.mp3", GENERATED),
			new Station("dubstep", "Dub Step Beyond", "Dubstep / Deep Bass", "Bass",
					"https://ice1.somafm.com/dubstep-128-mp3", SOMAFM),
			new Station("ebsm", "EBSM", "Industrial Bass / Body Music", "Bass", "https://stream.nightride.fm/ebsm.mp3",
					NIGHTRIDE),
			// Electronic
			new Station("mytunes-pulse", "myTunes Pulse", "Techno / Generated", "Electronic", "audio/mytunes-pulse.mp3",
					GENERATED),
			new Station("spacestation", "Space Station", "Electronic", "Electronic",
					"https://ice1.somafm.com/spacestation-128-mp3", SOMAFM),
			new Station("cliqhop", "cliqhop idm", "Intelligent Dance Music", "Electronic",
					"https://ice1.somafm.com/cliqhop-128-mp3", SOMAFM),
			new Station("spacesynth", "Spacesynth FM", "Spacesynth / Italo", "Electronic",
					"https://stream.nightride.fm/spacesynth.mp3", NIGHTRIDE),
			// Trance
			new Station("mytunes-drift", "myTunes Drift", "Trance / Generated", "Trance", "audio/mytunes-drift.mp3",
					GENERATED),
			new Station("thetrip", "The Trip", "Progressive House / Trance", "Trance",
					"https://ice1.somafm.com/thetrip-128-mp3", SOMAFM),
			// Wave
			new Station("mytunes-nightdrive", "myTunes Nightdrive", "Synthwave / Generated", "Wave",
					"audio/mytunes-nightdrive.mp3", GENERATED),
			new Station("u80s", "Underground 80s", "Synthpop / New Wave", "Wave",
					"https://ice1.somafm.com/u80s-128-mp3", SOMAFM),
			new Station("vaporwaves", "Vaporwaves", "Vaporwave", "Wave", "https://ice1.somafm.com/vaporwaves-128-mp3",
					SOMAFM),
			new Station("nightride", "Nightride FM", "Synthwave / Retrowave", "Wave",
					"https://stream.nightride.fm/nightride.mp3", NIGHTRIDE),
			new Station("datawave", "Datawave FM", "Datawave / Cyber", "Wave",
					"https://stream.nightride.fm/datawave.mp3", NIGHTRIDE),
			// Hacker
			new Station("mytunes-terminal", "myTunes Terminal", "IDM / Generated", "Hacker",
					"audio/mytunes-terminal.mp3", GENERATED),
			new Station("defcon", "DEF CON Radio", "Hacker / Electro", "Hacker",
					"https://ice1.somafm.com/defcon-128-mp3", SOMAFM),
			new Station("darksynth", "Darksynth FM", "Darksynth / Dark Electro", "Hacker",
					"https://stream.nightride.fm/darksynth.mp3", NIGHTRIDE));

	public List<Station> all() {
		return STATIONS;
	}

	/** Category names in menu order: first appearance in the catalogue wins. */
	public List<String> categories() {
		return STATIONS.stream().map(Station::category).distinct().toList();
	}

	public List<Station> byCategory(String category) {
		return STATIONS.stream().filter((station) -> station.category().equals(category)).toList();
	}

	public Station first() {
		return STATIONS.getFirst();
	}

	public Optional<Station> byId(String id) {
		return STATIONS.stream().filter((station) -> station.id().equals(id)).findFirst();
	}

	public Station byIdOrFirst(String id) {
		return byId(id).orElseGet(this::first);
	}

	public Station next(String id) {
		return relative(id, 1);
	}

	public Station previous(String id) {
		return relative(id, -1);
	}

	private Station relative(String id, int offset) {
		int size = STATIONS.size();
		int index = STATIONS.indexOf(byIdOrFirst(id));
		return STATIONS.get(Math.floorMod(index + offset, size));
	}

}
